pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Build'){
      agent{
        docker { image 'maven:3.8.1-adoptopenjdk-11'}
      }
      steps{
        sh 'mvn --version'
      }
      
    }
  }
}
